assistant/assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from decorator_include import decorator_include

urlpatterns = [
    path('', include('main.urls')),
    path('auth/', include('auth_extension.urls')),
    path('budget/', decorator_include(login_required, 'budget.urls')),
    path('todo/', decorator_include(login_required, 'todo.urls')),
    path('goals/', decorator_include(login_required, 'goals.urls')),
    path('admin/', admin.site.urls),
]

assistant/main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

assistant/main/models.py
from django.db import models

# Create your models here.

assistant/todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType

from goals.models import Goal


DEFAULT_CATEGORY = 1


class Category(models.Model):
    """
    Category for the tasks
    """
    title = models.CharField('Category title', max_length=40)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True,
                             on_delete=models.CASCADE, verbose_name='Own to user')

    class Meta:
        unique_together = (("title", "user"),)

    def delete(self, *args, **kwargs):
        """
        Deprecate deletion of the Default category
        """
        if self.id == DEFAULT_CATEGORY:
            raise Exception('You cannot delete this Category')
        super(Category, self).delete(*args, **kwargs)

    @property
    def get_category_tree(self):
        """
        Return string representation of this category with all its parents
        'parent/sub1/sub2/self'
        """
        cat = self
        cats = [cat.title]
        while cat.parent is not None:
            cat = cat.parent
            cats.insert(0, cat.title)

        return '/'.join(cats)

    @property
    def is_leaf(self):
        """
        Returns True if category don't have children, False otherwise
        """
        return self.category_set.all().count() == 0

    def get_all_children(self):
        """Returns all child categories"""
        children = [self]
        nodes = [self]
        while nodes:
            node = nodes.pop()
            cats = list(node.category_set.all())
            children = children + cats
            for cat in cats:
                if cat.is_leaf:
                    continue
                nodes.append(cat)

        return children

    def __str__(self):
        return self.title


class Files(models.Model):
    """
    Files that can be connected to the Task or other models
    """
    title = models.CharField('Title', max_length=50)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    upload = models.FileField('File', upload_to='uploads/')


class Task(models.Model):
    NEW = 0
    PROGRESS = 1
    POSTPONE = 2
    DONE = 3
    CANCELED = 4
    STATUSES = (
        (NEW, 'New'),
        (PROGRESS, 'In progress'),
        (POSTPONE, 'Postpone'),
        (DONE, 'Done'),
        (CANCELED, 'Canceled')
    )
    UI = 0
    UnI = 1
    nUI = 2
    nUnI = 3
    SIGNIFICANCE = (
        (UI, 'Urgent and important'),
        (UnI, 'Urgent and not important'),
        (nUI, 'Not urgent and important'),
        (nUnI, 'Not urgent and not important')
    )

    title = models.CharField('Title', max_length=120)
    description = models.TextField('Description', null=True, blank=True)
    category = models.ForeignKey(Category, default=DEFAULT_CATEGORY, on_delete=models.SET_DEFAULT)
    deadline = models.DateTimeField('Deadline', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='User')
    status = models.IntegerField('Status', choices=STATUSES, default=0)
    significance = models.IntegerField('Significance', choices=SIGNIFICANCE, default=0)
    files = GenericRelation(Files)
    goal = models.ForeignKey(Goal, null=True, blank=True, default=None,
                             on_delete=models.CASCADE, verbose_name='For goal')

    def delete(self, *args, **kwargs):
        self.status = self.CANCELED
        self.save()

    def get_main_category(self):
        """
        Returns the main category for the task
        """
        if not self.category.parent:
            return self.category

        cat = self.category.parent
        while cat.parent:
            cat = cat.parent
        return cat

    def __str__(self):
        return f'{self.title} ({self.category}). Due to {self.deadline}'

assistant/main/views.py
from datetime import date
from django.db.models import Q
from django.shortcuts import render

from todo.models import Task, Category
from goals.models import Goal


def index(request):
    context = {}
    if request.user.is_authenticated:
        tasks = Task.objects.select_related('category').filter(user=request.user,
                                    status__in=[Task.NEW, Task.PROGRESS, Task.POSTPONE]).order_by('category', '-status')
        goals = Goal.objects.filter(user=request.user,
                                    status__in=[Goal.NEW, Goal.PROGRESS])
        context = {
            'new_tasks_number': tasks.count(),
            'goals_number': goals.count()
        }
        tasks = tasks.filter(Q(deadline__date__lte=date.today()) | Q(deadline=None))
        cats = {}
        for t in tasks:
            cat = t.get_main_category().title
            cats[cat] = cats.get(cat, []) + [t]
        context['categories'] = cats

    return render(request, 'index.html', context)

assistant/main/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
{% load staticfiles %}
{% load main_extras %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Assistant</title>

    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
{#    <link href="{% static 'css/assistant.css' %}" rel="stylesheet">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/assistant.css' %}">

</head>

<body id="page-top">

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="{% url 'index' %}">Assistant</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for..." aria-label="Search"
                   aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger">{% get_today_task_number user %}</span>
                </a>
            </li>
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <span class="badge badge-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        {% endif %}
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'profile_page' %}">Profile page</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'register' %}">Register new account</a>
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                {% endif %}

            </div>
        </li>
    </ul>

</nav>

<div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
{#        <li class="nav-item">#}
{#            <a class="nav-link" href="index.html">#}
{#                <i class="fas fa-fw fa-tachometer-alt"></i>#}
{#                <span>Dashboard</span>#}
{#            </a>#}
{#        </li>#}
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks' %}">
                    <i class="fas fa-fw fa-tasks"></i>
                    <span>Tasks</span>
                </a>

                {% get_user_categories user %}

            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main_goals' %}">
                    <i class="fas fa-fw fa-fighter-jet"></i>
                    <span>Goals</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-sticky-note"></i>
                    <span>Notes</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-hand-holding-usd"></i>
                    <span>Budget</span></a>
            </li>
        {% endif %}
    </ul>

    <div id="content-wrapper">
        <div class="container-fluid">
            {% for message in messages %}
                {% get_bootstrap_alert_msg_css_name message.tags as alert_tag %}
                <div class="alert alert-{{ alert_tag }}">{{ message }}</div>
            {% endfor %}
            {% block main %} {% endblock %}
        </div>

        <!-- Sticky Footer -->
        <footer class="sticky-footer">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright © Your Website 2018</span>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="../../auth_extension/templates/login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin.min.js' %}"></script>

<!--Custom scripts-->
<script src="{% static 'js/assistant.js' %}"></script>

</body>

</html>

assistant/main/templates/cats.html
<div class="dropdown-menu" aria-labelledby="pagesDropdown">
    <a class="dropdown-item" href="{% url 'tasks' %}">All</a>
    <div class="dropdown-divider"></div>
    {% for cat in cats %}
        <a class="dropdown-item" href="{% url 'tasks_by_category' category_id=cat.id %}">{{ cat.get_category_tree }}</a>
    {% endfor %}
    <div class="dropdown-divider"></div>
    {% for cat in default %}
        <a class="dropdown-item" href="{% url 'tasks_by_category' category_id=cat.id %}">{{ cat.get_category_tree }}</a>
    {% endfor %}
</div>

assistant/main/templates/index.html
{% extends "base.html" %}

{% block content %}

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Overview</li>
    </ol>

    {% if user.is_authenticated %}
        <!-- Icon Cards-->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-warning o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-list"></i>
                        </div>
                        <div class="mr-5">{{ new_tasks_number }} Tasks!</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="{% url 'tasks' %}">
                        <span class="float-left">View Details</span>
                        <span class="float-right"><i class="fas fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-success o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-fighter-jet"></i>
                        </div>
                        <div class="mr-5">{{ goals_number }} Goals!</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="{% url 'main_goals' %}">
                        <span class="float-left">View Details</span>
                        <span class="float-right"><i class="fas fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-sticky-note"></i>
                        </div>
                        <div class="mr-5">Notes!</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="#">
                        <span class="float-left">View Details</span>
                        <span class="float-right"><i class="fas fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-secondary o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-hand-holding-usd"></i>
                        </div>
                        <div class="mr-5">Budget!</div>
                    </div>
                    <a class="card-footer text-white clearfix small z-1" href="#">
                        <span class="float-left">View Details</span>
                        <span class="float-right"><i class="fas fa-angle-right"></i></span>
                    </a>
                </div>
            </div>
        </div>

        {% if categories %}
            <div class="card mb-3">
                <div class="card-header">
                    <i class="fas fa-tasks"></i>
                    Your tasks for today
                    <a href="{% url 'add_task' %}?next={{ request.path|urlencode }}"
                       class="btn btn-dark float-sm-right">Add new task</a>
                </div>
                <div class="card-body">
                    <table class="table table-bordered" id="{{ cat.id }}" width="100%"
                           cellspacing="0" style="display: table; font-size: small; table-layout: fixed">
                        <thead>
                            <tr>
                                <th>Category</th>
                                <th>Task</th>
                                <th>Goal</th>
                                <th>
                                    Status<a href="{% url 'tasks' %}?sort=status"><i class="fas fa-sort-down fa-fw"></i></a>
                                </th>
                                <th>
                                    Significance<a href="{% url 'tasks' %}?sort=significance"><i class="fas fa-sort-down fa-fw"></i></a>
                                </th>
                                <th>
                                    Deadline<a href="{% url 'tasks' %}?sort=deadline"><i class="fas fa-sort-down fa-fw"></i></a>
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for cat, tasks in categories.items %}
                            {% for task in tasks %}
                                <a href="{% url 'edit_task' task_id=task.id %}?next={{ request.path|urlencode }}">
                                    <tr>
                                        <td>{{ task.category.get_category_tree }}</td>
                                        <td>
                                            <a href="{% url 'edit_task' task_id=task.id %}?next={{ request.path|urlencode }}">
                                                {{ task.title }}</a></td>
                                        <td>{{ task.goal.title }}</td>
                                        <td>{{ task.get_status_display }}</td>
                                        <td>{{ task.get_significance_display }}</td>
                                        <td>{{ task.deadline|date:'d-m-Y' }}</td>
                                        <td>
                                            <a href="{% url 'edit_task' task_id=task.id %}?next={{ request.path|urlencode }}"><i
                                                    class="fas fa-edit"></i></a>
                                            <a href="{% url 'done_task' task_id=task.id %}?next={{ request.path|urlencode }}"><i
                                                    class="fas fa-check"></i></a>
                                            <a href="{% url 'cancel_task' task_id=task.id %}?next={{ request.path|urlencode }}"><i
                                                    class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>
                                </a>
                            {% endfor %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer small text-muted"></div>
            </div>
        {% endif %}

        <!-- Area Chart Example-->
        <!--<div class="card mb-3">-->
        <!--<div class="card-header">-->
        <!--<i class="fas fa-chart-area"></i>-->
        <!--Area Chart Example-->
        <!--</div>-->
        <!--<div class="card-body">-->
        <!--<canvas id="myAreaChart" width="100%" height="30"></canvas>-->
        <!--</div>-->
        <!--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>-->
        <!--</div>-->
    {% else %}
        <h2>Welcome to the Personal Assistant!</h2>
        <p>What is Personal assistant? It is a service that allows you to save all in one place!</p>
        <br>
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-warning o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-tasks"></i>
                        </div>
                        <div class="mr-5">Tasks!</div>
                    </div>
                    <span class="card-footer text-white clearfix small z-1">
                        <h5>All that you need to do in one place. Separated by categories, by urgent and important.
                            You also can add additional attachments and notes to quick refresh all in your mind.
                            And deadlines if you want and get notifications about current tasks!
                            Also you can create a ToDo list, filter by categories, importance, deadline!</h5>
                    </span>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-success o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-fighter-jet"></i>
                        </div>
                        <div class="mr-5">Goals!</div>
                    </div>
                    <span class="card-footer text-white clearfix small z-1">
                        <h5>We have heard a lot about the importance of creating goals to achieve something that we want
                            in this
                            life. But how often do you do it? Here you can do it. Break them into sub-goals, create
                            tasks, visualize
                            your path, control your path and, of course, track your progress towards your goals!</h5>
                    </span>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-sticky-note"></i>
                        </div>
                        <div class="mr-5">Notes!</div>
                    </div>
                    <span class="card-footer text-white clearfix small z-1">
                        <h5>How often you need to save something for the future. Some recipe, useful links, articles,
                            books that
                            your want to read, films that you are going to see somehow?
                            Where are these information? Some in the browser boockmarks, in the notes on laptop, in the
                            files just
                            downloaded to the computer. Here you can keep all in one place!</h5>
                    </span>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-secondary o-hidden h-100">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="fas fa-fw fa-hand-holding-usd"></i>
                        </div>
                        <div class="mr-5">Budget!</div>
                    </div>
                    <span class="card-footer text-white clearfix small z-1">
                        <h5>We all know the importance of tracking income and expenses for your financial condition.
                            Maybe you
                            even try to do it. We have an accountant in business, but what about your home budget? Can
                            you tell me how
                            much you spend on food, transport, utilities, clothing or entertainment? Where the black
                            hole of your
                            budget? How to optimize it? We can help with it!</h5>
                    </span>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}